PUT http://localhost:4100/retailer/add-item
Content-Type: application/json

{
    "shop_id":"63fa276d83ce14ae47145255",
    "shop_name":"Shop Name",
    "name":"Product Name",
    "description":"Product Description",
    "price":100,
    "qty":10,
    "image_link":"sfhsfuswufhns"

}