POST http://localhost:4100/signup
Content-Type: application/json

{
    "username":"abhay",
    "email":"abhay@gmail.com",
    "password":"abhay",
    "location":{
        "latitude":21.44,
        "longitude":73.434
    },
    "address":"Help sfyewhb"

}