POST http://localhost:4100/retailer/signup
Content-Type: application/json

{
    "username":"shreya3223",
    "name":"shreya",
    "address":"sdbhbshfb",
    "email":"shreya@gmail.com",
    "password":"shreya",
    "location":"20,100"

}